name: Generate ASCII artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: execute cowsay cmd
          run: cowsay -f dragon "I love you Elise West" >> dragon.txt

        - name: test if file exists
          run: grep -i "elise" dragon.txt

        - name: read file
          run: cat dragon.txt

        - name: checkout repo files
          run: ls