name: generate ASCII artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: execute shell script
          run: |
            ls -ltra
            chmod +x ascii-script.sh
            ./ascii-script.sh