name: testing workflows

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checks out repo
          uses: actions/checkout@v4

        - name: welcome, list files, read readme
          run: |
            echo "hello"
            ls -ltra
            cat README.md
        
