name: testing workflows

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checks out repo
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "hello"

        - name: list files
          run: ls

        - name: read readme
          run: cat README.md