name: Exploring variables and secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

#can define environmental variables at step level, job level, or workflow level
#can also use them at repository level or environment level
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          run: docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}$IMAGE_NAME:latest
        
        - name: Docker login
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            
        - name: Docker push
          run: docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker run
          run: docker run -d -p 8000:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest